export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import NavbarComponenet from "@/app/components/navbar";
import RootProvider from "@/provider/providers";
import { GlobalContextProvider } from "@/provider/contextProvider";
import ListOfPool from "./components/poolListPopUp";
import "../styles/globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RootProvider>
          <GlobalContextProvider>
            <NavbarComponenet />
            <ListOfPool />
            {children}
          </GlobalContextProvider>
        </RootProvider>
      </body>
    </html>
  );
}
