export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import NavbarComponenet from "@/app/components/navbar";
import RootProvider from "@/provider/providers";
import { GlobalContextProvider } from "@/provider/contextProvider";
import ListOfPool from "./components/popups/poolListPopUp";
import "../styles/globals.css";
import TransactionComponent from "./components/transactionComponenet";
import ListOfPay from "./components/popups/payOptionsPopUp";
import WithdrawalPopUp from "./components/popups/withdrawalPopUp";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RootProvider>
          <GlobalContextProvider>
            <NavbarComponenet />
            <ListOfPool />
            {children}
            <ListOfPay />
            <WithdrawalPopUp />
            <TransactionComponent />
          </GlobalContextProvider>
        </RootProvider>
      </body>
    </html>
  );
}
